package com.ems;

/**
 * 
 * @author geloxh
 * 
 */

import com.sun.java.swing.plaf.windows.WindowsBorders;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class NewEquipment extends javax.swing.JFrame {
    Connection connection = null;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form for NewEquipment
     */
    public NewEquipment() {
        super("New Equipment");
        initComponents();
        connection = JavaConnectionDataBase.connectToDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EquipDescriptionTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EquipDescriptionTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EquipDescriptionTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EquipDescriptionTextField5 = new javax.swing.JTextField();
        NewEquipmentPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EquipmentCodeLabel = new javax.swing.JLabel();
        EquipmentDescriptionLabel = new javax.swing.JLabel();
        EquipmentDescriptionTextField = new javax.swing.JTextField();
        EquipmentNameLabel = new javax.swing.JLabel();
        EquipNameTextField = new javax.swing.JTextField();
        EquipmentCodeTextField = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTextField = new javax.swing.JTextField();
        SupplierLabel = new javax.swing.JLabel();
        SupplierTextField = new javax.swing.JTextField();
        ClassroomTextField = new javax.swing.JTextField();
        ClassroomLabel = new javax.swing.JLabel();

        EquipDescriptionTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipDescriptionTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipDescriptionTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("From Teacher");

        EquipDescriptionTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipDescriptionTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipDescriptionTextField3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("From Teacher");

        EquipDescriptionTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipDescriptionTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipDescriptionTextField4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("From Teacher");

        EquipDescriptionTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipDescriptionTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipDescriptionTextField5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewEquipmentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Equipment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-add-icon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EquipmentCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipmentCodeLabel.setText("Equipment Code");

        EquipmentDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipmentDescriptionLabel.setText("Equipment Description");

        EquipmentDescriptionTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipmentDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentDescriptionTextFieldActionPerformed(evt);
            }
        });

        EquipmentNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EquipmentNameLabel.setText("Equipment Name");

        EquipNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        EquipmentCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuantityLabel.setText("Quantity");

        QuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextFieldActionPerformed(evt);
            }
        });

        SupplierLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierLabel.setText("From Teacher");

        SupplierTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierTextFieldActionPerformed(evt);
            }
        });

        ClassroomTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClassroomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassroomTextFieldActionPerformed(evt);
            }
        });

        ClassroomLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClassroomLabel.setText("Classroom");

        javax.swing.GroupLayout NewEquipmentPanelLayout = new javax.swing.GroupLayout(NewEquipmentPanel);
        NewEquipmentPanel.setLayout(NewEquipmentPanelLayout);
        NewEquipmentPanelLayout.setHorizontalGroup(
            NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addComponent(EquipmentCodeLabel)
                        .addGap(82, 82, 82)
                        .addComponent(EquipmentCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addComponent(EquipmentNameLabel)
                        .addGap(79, 79, 79)
                        .addComponent(EquipNameTextField))
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addComponent(EquipmentDescriptionLabel)
                        .addGap(46, 46, 46)
                        .addComponent(EquipmentDescriptionTextField))
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addComponent(QuantityLabel)
                        .addGap(131, 131, 131)
                        .addComponent(QuantityTextField))
                    .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                        .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierLabel)
                            .addComponent(ClassroomLabel))
                        .addGap(99, 99, 99)
                        .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierTextField)
                            .addComponent(ClassroomTextField))))
                .addContainerGap())
        );
        NewEquipmentPanelLayout.setVerticalGroup(
            NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewEquipmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipmentCodeLabel)
                    .addComponent(EquipmentCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipmentNameLabel)
                    .addComponent(EquipNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipmentDescriptionLabel)
                    .addComponent(EquipmentDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplierLabel)
                    .addComponent(SupplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassroomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassroomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(NewEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewEquipmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewEquipmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(701, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EquipmentDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipmentDescriptionTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DashBoard dashboard = new DashBoard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sqlInsertNewEquipment = "INSERT INTO Equipment(EquipmentCode, EquipmentName, EquipmentDescription, Quantity, Supplier, Classroom) VALUES (?,?,?,?,?,?)";
        try {
            preparedStatement = connection.prepareStatement(sqlInsertNewEquipment);
            preparedStatement.setString(1, EquipmentCodeTextField.getText());
            preparedStatement.setString(2, EquipNameTextField.getText());
            preparedStatement.setString(3, EquipmentDescriptionTextField.getText());
            preparedStatement.setString(4, QuantityTextField.getText());
            preparedStatement.setString(5, SupplierTextField.getText());
            preparedStatement.setString(6, ClassroomTextField.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "New Equipment Added Successfully");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to create new equipment. Please contact with teacher");
                 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EquipDescriptionTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipDescriptionTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipDescriptionTextField1ActionPerformed

    private void QuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTextFieldActionPerformed

    private void SupplierTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierTextFieldActionPerformed

    private void EquipDescriptionTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipDescriptionTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipDescriptionTextField3ActionPerformed

    private void EquipDescriptionTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipDescriptionTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipDescriptionTextField4ActionPerformed

    private void EquipDescriptionTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipDescriptionTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipDescriptionTextField5ActionPerformed

    private void ClassroomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassroomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassroomTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassroomLabel;
    private javax.swing.JTextField ClassroomTextField;
    private javax.swing.JTextField EquipDescriptionTextField1;
    private javax.swing.JTextField EquipDescriptionTextField3;
    private javax.swing.JTextField EquipDescriptionTextField4;
    private javax.swing.JTextField EquipDescriptionTextField5;
    private javax.swing.JTextField EquipNameTextField;
    private javax.swing.JLabel EquipmentCodeLabel;
    private javax.swing.JTextField EquipmentCodeTextField;
    private javax.swing.JLabel EquipmentDescriptionLabel;
    private javax.swing.JTextField EquipmentDescriptionTextField;
    private javax.swing.JLabel EquipmentNameLabel;
    private javax.swing.JPanel NewEquipmentPanel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTextField;
    private javax.swing.JLabel SupplierLabel;
    private javax.swing.JTextField SupplierTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
